version: '2'

services:
  eureka:
    build: ./Eureka
    ports:
      - '8761:8761'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  gateway:
    build: ./Gateway-service
    ports:
      - '8080:8080'
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: foodie
      MYSQL_USER: mss
      MYSQL_PASSWORD: password
  user-microservice:
    build: ./User
    ports:
      - '8081:8081'
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  restaurant-microservice:
    build: ./Restaurant
    ports:
      - '8082:8082'
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  review-microservice:
    build: ./Review
    ports:
      - '8083:8083'
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=dev