server:
  ports:
    - "8081:8081"

spring:
  application:
    name: user-microservice
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: mysql
    url: jdbc:mysql://db:3306/foodie
    username: mss
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  eureka:
    client:
      service-url:
        defaultZone: {EUREKA_SERVER: http://docker.for.mac.host.internal:8761/eureka}

#  eureka:
#    instance:
#      hostname: localhost