server:
  ports:
    - "8082:8082

spring:
  application:
    name: restaurant-microservice
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: mysql
    url: jdbc:mysql://db:3306/foodie
    username: mss
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  eureka:
    instance:
      hostname: eureka