server:
  ports:
    - "8080:8080"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: user-microservice:8081
          predicates:
            - Path=/user/**
        - id: restaurants
          uri: http://localhost:8082
          predicates:
            - Path=/restaurant/**
        - id: reviews
          uri: http://localhost:8083
          predicates:
            - Path=/review/**

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: {EUREKA_SERVER: http://docker.for.mac.host.internal:8761/eureka}
    healthcheck:
      enabled: true
    registered-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info